AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart-Photo-Album-Application

Parameters:
  OpenSearchName:
    Type: String
    Description:
      "photos"

  NamePrefix:
      Type: String
      Description: Prefix to add to Lex resource names
      Default: WebUi
      MinLength: 3
      MaxLength: 32
      AllowedPattern: '^[a-zA-Z\._]+$'
      ConstraintDescription: >
          Must conform with the permitted Lex Bot name pattern.

  ShouldDeleteBot:
      Type: String
      Default: true
      AllowedValues:
        - true
        - false
      Description: >
          If set to True, the Lex bot and associated resources will
          be deleted when the stack is deleted. Otherwise, the bot
          will be preserved.


Resources:
  S3BUCKET2:
    Type: 'AWS::S3::Bucket'
    Properties: 
        BucketName: smart-photo-album-bucket
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
  
  S3BUCKET1:
    Type: 'AWS::S3::Bucket'
    Properties:
        BucketName: smart-photo-album-ui
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

  OpenSearchInstance:
    Type: AWS::OpenSearchService::Domain
    Properties: 
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
              - "arn:aws:iam::544883597344:root"
              - "arn:aws:iam::544883597344:user/dev"
              - "arn:aws:iam::544883597344:user/YashLimbachiya"
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchName}/*
      DomainName: !Ref OpenSearchName
      ClusterConfig:
        InstanceType: t2.small.search
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10

  LexBot:
    Type: Custom::LexBot
    Properties:
#        ServiceToken: !GetAtt LexBotLambda.Arn
        BotName: 'PhotoBot'
        BotAlias: 'PhotoChatbot'
        NamePrefix: !Ref NamePrefix
        ShouldDelete: !Ref ShouldDeleteBot
