AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  index-photosFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: index-photos-2
      Handler: lambda-function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda-functions/index-photos/
  search-photosFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: search-photos-2
      Handler: lambda-function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda-functions/search-photos/
